<?xml version="1.0"?>
<robot name="theron_base" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="theron_base" params="publish_bf hq">

    <xacro:property name="PI" value="3.1415926535897931"/>
    <!-- xacro:property name="wheel_width" value="0.150" / -->

    <!-- BASE FOOTPRINT -->
    <xacro:if value="${publish_bf}">
      <link name="base_footprint"/>
      <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${wheel_radius - wheel_offset_z}" rpy="0 0 0"/>
        <parent link="base_footprint"/>
        <child link="base_link" />
      </joint>
    </xacro:if>

    <!-- BASE_LINK -->
    <link name="base_link">
      <inertial>
        <mass value="45" />
        <origin xyz="0.0 0.0 0.0" />
        <xacro:solid_cuboid_inertia m="45" w="0.3275" h="0.2775" d="0.1525" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <xacro:if value="${hq}">
          <geometry>
            <mesh filename="file://$(find rb_theron_description)/meshes/bases/theron_base.stl"/>
          </geometry>
        </xacro:if>
        <xacro:unless value="${hq}">
          <geometry>
            <box size="0.700 0.600 0.350"/>
          </geometry>
        </xacro:unless>
        <material name="darkgrey">
          <color rgba="0.1 0.1 0.1 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0.005" rpy="0 0 0 " />
        <geometry>
          <mesh filename="file://$(find rb_theron_description)/meshes/bases/theron_base.dae"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>
</robot>
