base_local_planner: teb_local_planner/TebLocalPlannerROS

TebLocalPlannerROS:
  odom_topic: robotnik_base_control/odom
  map_frame: robot_odom

  # Trajectory

  teb_autosize: True
  dt_ref: 0.2
  dt_hysteresis: 0.02
  min_samples: 5
  global_plan_overwrite_orientation: True
  global_plan_viapoint_sep: 0.5
  max_global_plan_lookahead_dist: 5.0
  force_reinit_new_goal_dist: 1.0
  feasibility_check_no_poses: 5
  shrink_horizon_backup: true
  exact_arc_length: false
  shrink_horizon_min_duration: 10


  # Robot

  max_vel_x: 0.5 #1.0
  max_vel_x_backwards: 0.03
  max_vel_theta: 0.5 #1.0
  acc_lim_x: 0.5
  acc_lim_theta: 0.5
  min_turning_radius: 0.0
  wheelbase: 0.0
  cmd_angle_instead_rotvel: false
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "line" # Let's use line to avoid CPU overhead
    # radius: 0.3 # for type "circular"
    line_start: [-0.2, 0.0] # for type "line"
    line_end: [0.2, 0.0] # for type "line"
    #front_offset: 0.2 # for type "two_circles"
    #front_radius: 0.2 # for type "two_circles"
    #rear_offset: 0.2 # for type "two_circles"
    #rear_radius: 0.2 # for type "two_circles"
    #vertices: [[0.140, 0.148], [-0.250, 0.148], [-0.250, -0.148], [0.140, -0.148]] # for type "polygon"

  # GoalTolerance

  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.03
  free_goal_vel: False

  # Obstacles

  min_obstacle_dist: 0.317 # inflation over footprint_model. Should cover complete robot
  inflation_dist: 0.33 # greater than min_obstacle_dist to take effect
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30
  obstacle_association_force_inclusion_factor: 1.5
  obstacle_association_cutoff_factor: 5.0
  costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
  #costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSRANSAC"
  #costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSMCCH"
  #costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSConcaveHull"
  #costmap_converter_plugin: "" # deactivate plugin
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5
  # costmap_converter/CostmapToLinesDBSRANSAC:
  #    cluster_max_distance: 0.4

  # Optimization

  no_inner_iterations: 7
  no_outer_iterations: 5
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.025
  weight_max_vel_x: 5
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 10000
  weight_kinematics_forward_drive: 1000
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 10
  weight_obstacle: 50
  weight_inflation: 5
  weight_dynamic_obstacle: 10 # not in use yet
  weight_viapoint: 50
  weight_adapt_factor: 2
  selection_alternative_time_cost: False

  # Homotopy Class Planner

  enable_homotopy_class_planning: True
  enable_multithreading: True
  simple_exploration: False
  max_number_classes: 2
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 4.0
  selection_viapoint_cost_scale: 1.0
  selection_alternative_time_cost: False
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 1.0
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: False
